Feature/my record gp
dal-cho/adme-front pull request #145
Opened 2023-06-17 07:39 UTC by great-psycho

- my_record 페이지  js 작업
- js 작성하며 다른 파일에 놓친 기능들 수정

2023-06-17 08:16 UTC, great-psycho commented
병합에 있어  충돌 해결을 위해 부득이 하게 파일 위치가 정리되지 않았습니다. 
pr 이 완료되면 다시 한번 전체 점검 하면서 파일 경로 수정할 계획입니다.

2023-06-17 16:22 UTC, haedal-uni approved these changes
확인했습니다.

2023-06-17 16:29 UTC, haedal-uni requested changes
Network graph

2023-06-19 04:16 UTC, haedal-uni approved these changes
확인했습니다.

2023-06-19 04:22 UTC, merged